# Generated by Django 3.1 on 2020-11-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rauthor',
            field=models.TextField(default=''),
        ),
    ]
