# Generated by Django 3.1 on 2020-11-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_rauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='filedata',
            field=models.FileField(default='', upload_to='uploadedfiles'),
        ),
    ]
