# Generated by Django 3.1 on 2020-10-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0007_profile_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='college',
            field=models.CharField(default='', max_length=200),
        ),
    ]
