# Generated by Django 3.1 on 2020-10-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0008_auto_20201015_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dob',
        ),
    ]
