# Generated by Django 3.1 on 2020-10-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0009_remove_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
