# Generated by Django 3.1 on 2020-10-16 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0011_todolist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='userlist',
        ),
        migrations.AddField(
            model_name='todolist',
            name='usertask',
            field=models.CharField(default='', max_length=500),
        ),
    ]
