# Generated by Django 3.1 on 2020-10-16 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0012_auto_20201016_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
