# Generated by Django 3.1 on 2020-10-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0016_todolist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ToDoList',
        ),
    ]
