# Generated by Django 3.1 on 2020-10-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0020_todolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='DataToDo',
        ),
    ]
