# Generated by Django 3.1 on 2020-10-16 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0021_auto_20201016_1316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataToDo',
        ),
    ]
