# Generated by Django 3.1 on 2020-10-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0022_delete_datatodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
