# Generated by Django 3.1 on 2020-10-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0023_abcd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ABCD',
        ),
    ]
