# Generated by Django 3.1 on 2020-10-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0024_delete_abcd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoListData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
