# Generated by Django 3.1 on 2020-10-18 08:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HOME', '0026_todolistdata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistdata',
            name='task',
        ),
        migrations.AddField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 14, 26, 29, 444379)),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
