# Generated by Django 3.1 on 2020-10-18 09:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0028_auto_20201018_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 18, 14, 31, 11, 608135)),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HOME.profile'),
        ),
    ]
