# Generated by Django 3.1 on 2020-10-24 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0032_auto_20201018_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 24, 20, 40, 58, 299821)),
        ),
    ]
