# Generated by Django 3.1 on 2020-10-28 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0036_auto_20201028_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 28, 17, 40, 44, 222639)),
        ),
    ]
