# Generated by Django 3.1 on 2020-10-30 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0037_auto_20201028_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='followersdata',
            name='isYourFollowers',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 30, 11, 56, 12, 396238)),
        ),
    ]
