# Generated by Django 3.1 on 2020-11-01 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0041_auto_20201101_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 12, 6, 47, 408875)),
        ),
        migrations.DeleteModel(
            name='UserFollowersandFollowing',
        ),
    ]
