# Generated by Django 3.1 on 2020-11-01 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0043_auto_20201101_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followersandfollowing',
            name='followers',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='followersandfollowing',
            name='following',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 12, 11, 1, 609457)),
        ),
    ]
