# Generated by Django 3.1 on 2020-11-01 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0044_auto_20201101_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followersandfollowing',
            old_name='userid',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 12, 13, 50, 101551)),
        ),
    ]
