# Generated by Django 3.1 on 2020-11-01 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0045_auto_20201101_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followersandfollowing',
            name='followers',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='followersandfollowing',
            name='following',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 12, 36, 42, 404480)),
        ),
    ]
