# Generated by Django 3.1 on 2020-11-16 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0047_auto_20201115_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 16, 22, 18, 4, 592886)),
        ),
    ]
