# Generated by Django 3.1 on 2020-11-17 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0048_auto_20201116_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followersandfollowing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 18, 33, 59, 211689)),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 18, 33, 59, 210690)),
        ),
    ]
