# Generated by Django 3.1 on 2020-11-17 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0052_auto_20201117_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followersandfollowing',
            name='created',
            field=models.DateField(default=datetime.date(2020, 11, 17)),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 18, 46, 32, 326705)),
        ),
    ]
