# Generated by Django 3.1 on 2020-11-17 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME', '0053_auto_20201117_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followersandfollowing',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todolistdata',
            name='taskcreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 17, 18, 47, 31, 509002)),
        ),
    ]
